# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=25)),
                ('status', models.CharField(default='', max_length=25)),
                ('opened', models.DateTimeField()),
                ('document', models.TextField(default='')),
            ],
            options={
                'db_table': 'bug',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('has_bug', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('num_messages', models.PositiveIntegerField(default=0)),
                ('document', models.TextField(default='')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ReviewBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bug')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
            options={
                'db_table': 'review_bug',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bug')),
            ],
            options={
                'db_table': 'vulnerability',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='bugs',
            field=models.ManyToManyField(through='app.ReviewBug', to='app.Bug'),
        ),
        migrations.AddField(
            model_name='bug',
            name='reviews',
            field=models.ManyToManyField(through='app.ReviewBug', to='app.Review'),
        ),
    ]
