# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 03:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='opened',
        ),
        migrations.AlterField(
            model_name='bug',
            name='document',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='review',
            name='document',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
