# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161021_0344'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX review_document_reviewed_files_idx '
            'ON review USING GIN'
            '((document -> \'reviewed_files\'));'
        ),
        migrations.RunSQL(
            'CREATE INDEX review_document_committed_files_idx '
            'ON review USING GIN'
            '((document -> \'committed_files\'));'
        )
    ]
