# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_custom_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_successful',
            new_name='was_committed',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='id',
            new_name='cve',
        ),
        migrations.RemoveField(
            model_name='review',
            name='has_bug',
        ),
        migrations.AddField(
            model_name='review',
            name='missed_vulnerability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='source',
            field=models.CharField(default='monorail', max_length=8),
        ),
    ]
