# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161230_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField()),
                ('sender', models.EmailField(max_length=254)),
                ('text', models.TextField(default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, default='')),
                ('base', models.TextField(db_index=True, default='')),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('pos', models.CharField(default='', max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message')),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
