# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='base',
            new_name='lemma',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='text',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
