# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170202_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bug')),
            ],
            options={
                'db_table': 'vulnerability_bug',
            },
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='cve',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='bug',
        ),
        migrations.AlterUniqueTogether(
            name='reviewbug',
            unique_together=set([('review', 'bug')]),
        ),
        migrations.AddField(
            model_name='vulnerabilitybug',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vulnerability'),
        ),
        migrations.AddField(
            model_name='bug',
            name='vulnerabilities',
            field=models.ManyToManyField(through='app.VulnerabilityBug', to='app.Vulnerability'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='bugs',
            field=models.ManyToManyField(through='app.VulnerabilityBug', to='app.Bug'),
        ),
        migrations.AlterUniqueTogether(
            name='vulnerabilitybug',
            unique_together=set([('vulnerability', 'bug')]),
        ),
    ]
