# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170202_2106')
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='frequency',
        ),
        migrations.AddField(
            model_name='token',
            name='position',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
