# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170207_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sentiment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
