# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_token_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chunk',
            field=models.CharField(default='', max_length=10),
        ),
    ]
