# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 18:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parse',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
