# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 15:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_polite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('parses', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
            options={
                'db_table': 'sentence',
            },
        ),
    ]
