# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parse',
        ),
        migrations.RemoveField(
            model_name='message',
            name='polite',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='token',
            name='message',
        ),
        migrations.AddField(
            model_name='token',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sentence')
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'complexity': {}, 'politeness': {}, 'sentiment': {}}),
        ),
    ]
