# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170425_1409'),
        ('app', '0010_add_token_chunk'),
    ]

    operations = [
    ]
