# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_token_sentence'),
        ('app', '0007_create_materialized_views'),
    ]

    operations = [
    ]
