# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20170509_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='token',
            name='uncertainty',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
