# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 05:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='path',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='patch',
            name='module_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patchset',
            name='modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        # Commands that follow were manually added to this auto-generated file
        migrations.RunSQL(
            'CREATE INDEX review_document_reviewed_modules_idx '
            'ON review USING GIN'
            '((document -> \'reviewed_modules\'));'
        ),
        migrations.RunSQL(
            'CREATE INDEX review_document_committed_modules_idx '
            'ON review USING GIN'
            '((document -> \'committed_modules\'));'
        )
    ]
