# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-23 03:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_module_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
