# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170620_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'complexity': {}, 'formality': {}, 'implicature': {}, 'informativeness': {}, 'politeness': {}, 'sentiment': {}}),
        ),
    ]
