# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170621_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posted', models.DateTimeField()),
                ('line', models.PositiveIntegerField()),
                ('author', models.EmailField(max_length=254)),
                ('text', models.TextField(default='')),
                ('is_useful', models.BooleanField(default=False)),
                ('by_reviewer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('num_added', models.IntegerField(default=0)),
                ('num_removed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'patch',
            },
        ),
        migrations.CreateModel(
            name='PatchSet',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('created', models.DateTimeField()),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review')),
            ],
            options={
                'db_table': 'patchset',
            },
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='review',
        ),
        migrations.AddField(
            model_name='message',
            name='sentences',
            field=models.ManyToManyField(to='app.Sentence'),
        ),
        migrations.AlterField(
            model_name='reviewbug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vulnerabilitybug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patch',
            name='patchset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PatchSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patch'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentences',
            field=models.ManyToManyField(to='app.Sentence'),
        ),
        migrations.AlterUniqueTogether(
            name='patchset',
            unique_together=set([('id', 'review')]),
        ),
        migrations.AlterUniqueTogether(
            name='patch',
            unique_together=set([('id', 'patchset')]),
        ),
    ]
