# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_token_is_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='clean_text',
            field=models.TextField(default=None, null=True),
        ),
    ]
