# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_jsonb_field_to_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_code',
        ),
    ]
