# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_token_is_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='clean_parses',
        ),
    ]
